name: payroll_app
description: "برنامه محاسبه حقوق و دستمزد فرایند کود و سم بافق - سال 1405"
publish_to: 'none'

version: 0.9.12-alpha+32

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Database
  sqflite_common_ffi: ^2.3.3
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  # State management
  provider: ^6.1.2

  # Persian / Date
  shamsi_date: ^1.0.4
  intl: ^0.20.2

  # PDF / Printing
  pdf: ^3.11.1
  printing: ^5.13.2

  # File operations
  file_picker: 8.3.7

  # Preferences for theme/accessibility persistence
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.24
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.1
  http: ^1.2.2
  crypto: ^3.0.5
  uuid: ^4.5.3

  # Dynamic Color (Material You)
  dynamic_color: ^1.8.1

  # Color Picker
  flutter_colorpicker: ^1.1.0
  excel: ^4.0.6
  image: ^4.3.0
  share_plus: ^12.0.2
  url_launcher: ^6.3.2
  window_manager: 0.5.1
  tray_manager: 0.5.3
  package_info_plus: ^9.0.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_secure_storage_windows:
    path: third_party/flutter_secure_storage_windows

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/fonts/
    - assets/data/
    - windows/runner/resources/app_icon.ico

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
